
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/mnt/hdd1/software/modules/sw/core/cmake/3.30/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.14.0-503.40.1.el9_5.x86_64 - x86_64
...
